### ISSUE TITLE
option to skip validation on nested struct if value is nil

### ISSUE THREAD

**Issue by twistedlog** [RussellLuo/validating#1]
There should be an option to skip validation of a nested struct if the nested struct's value is nil.

**Comment by RussellLuo** [comment]
This library tries to be small and **composite**, so any specific option will break this rule.

In the use case you mentioned, you can achieve it by combining [Assert](https://godoc.org/github.com/RussellLuo/validating#Assert) and [Lazy](https://godoc.org/github.com/RussellLuo/validating#Lazy). See [Nested struct pointer](https://github.com/RussellLuo/validating/blob/master/examples/nested-struct-pointer/main.go) for an example.

**Comment by RussellLuo** [comment]
As a supplement, it seems impossible to check whether a nested struct is nil or not, without using reflection?

**Comment by twistedlog** [comment]
That's correct without refection its not possible, yes i think using Assert and Lazy in Any clause works. 
Thanks.

**Comment by RussellLuo** [comment]
Yeah, `Any(Assert(...), Lazy(...))` works :)

**Comment by RussellLuo** [comment]
@twistedlog I am going to close this issue, you can create a new one if you encountered other problems :)
