### ISSUE TITLE
Asking for opinion

### ISSUE THREAD

**Issue by th0th** [RussellLuo/validating#11]
Hi @RussellLuo, thank you for making this! I tried other popular validation libraries but yours worked awesome for me.

I wrote some validation functions for more business logic kind of stuff and utilities, and planning to add more. I thought maybe we can consider adding a link for people with similar needs: https://github.com/th0th/validatingextra

Also, I wanted to ask your opinion on a function I wrote: [`PointerValue`](https://github.com/th0th/validatingextra/blob/main/main.go#L93)

For some stuff, I am using pointer struct fields like this:

```go
type Data struct {
  Email *string
}
```

And I wrote `PointerValue` to validate the pointer's value. Is there a better way to handle this kind of case?

**Comment by RussellLuo** [comment]
@th0th Great job! Feel free to append a link to this section [Extension validator factories](https://github.com/RussellLuo/validating#extension-validator-factories).

> Also, I wanted to ask your opinion on a function I wrote: [PointerValue](https://github.com/th0th/validatingextra/blob/main/main.go#L93)
> ...
> And I wrote PointerValue to validate the pointer's value. Is there a better way to handle this kind of case?

There is an example that demonstrates a similar use case by combining [All](https://pkg.go.dev/github.com/RussellLuo/validating/v3#All) and [Nonzero](https://pkg.go.dev/github.com/RussellLuo/validating/v3#Nonzero):

https://github.com/RussellLuo/validating/blob/2221f3bc6d595673764e113d264b366252b7e8d4/example_nested_struct_pointer_test.go#L23-L32

**Comment by RussellLuo** [comment]
Of course, that would be great! Feel free to submit a PR :)
