### ISSUE TITLE
[validator] would it be ok to have more business oriented validators?

### ISSUE THREAD

**Issue by benjaminch** [RussellLuo/validating#6]
Hello !

First of all, thanks a lot for this library ! :)

I was wondering if you would be open to PR introducing more business oriented validators to be used by higher level applications. I a; think of validators such as:
- email
- phone number
- website
- etc

If it makes sense to you, I am whiling to work on this PR :)

Thanks !

**Comment by RussellLuo** [comment]
Hi @benjaminch , sorry for the delayed reply.

`validating` is dedicated to be  a basic library, so it tries to be as simple (and minimal) as possible.

I would like to encourage you to create a new repo, **as an extension** of `validating`, to build common business-oriented validators. And I can update `validating`'s README to add an extension link to your repo :-)
